// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package matlab.jpar.client;

public final class JParClientImpl_Stub
    extends java.rmi.server.RemoteStub
    implements matlab.jpar.client.common.JParClient, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_taskIsDone_0;
    
    static {
	try {
	    $method_taskIsDone_0 = matlab.jpar.client.common.JParClient.class.getMethod("taskIsDone", new java.lang.Class[] {java.lang.String.class, java.lang.Object[].class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public JParClientImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of taskIsDone(String, Object[])
    public boolean taskIsDone(java.lang.String $param_String_1, java.lang.Object[] $param_arrayOf_Object_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_taskIsDone_0, new java.lang.Object[] {$param_String_1, $param_arrayOf_Object_2}, -203926969609157082L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
